version: '3'
services:
  rentalapp:
    build: ./
    volumes:
      - rentaldir:/var/www
    depends_on:
      - rentalapp-mysql
      - rentalapp-redis
    ports:
      - "9000:80"
  rentalapp-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: rentalapp
      MYSQL_ROOT_PASSWORD: root
  rentalapp-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - rentaldir:/var/www
    depends_on:
      - rentalapp
  rentalapp-redis:
    image: redis:alpine
    expose:
      - 6379
volumes:
  rentaldir:
